services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
      - client
    restart: always

  client:
    container_name: client
    hostname: client
    restart: always
    build:
      context: ./client
    ports:
      - "4321:4321"
    expose:
      - 4321
    depends_on:
      - server

  server:
    container_name: server
    hostname: server
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - minio
      - postgres

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DEFAULT_BUCKETS: "memory-site"
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
      - ./minio/minio-setup.sh:/docker-entrypoint-init.d/minio-setup.sh

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: memory_site
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  minio_data:
  postgres_data:

