services:
  server:
    container_name: server
    hostname: server
    restart: always
    build:
      context: ./server
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: "news-media"
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
      - ./minio/minio-setup.sh:/docker-entrypoint-init.d/minio-setup.sh

volumes:
  minio_data:
