# Generated by Django 5.1.7 on 2025-04-12 12:21

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterans', '0002_alter_veteranmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veteranmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.MediaStorage(), upload_to='veterans/', verbose_name='Загрузить фото'),
        ),
    ]
