# Generated by Django 5.1.7 on 2025-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterans', '0003_alter_veteranmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmodel',
            name='is_vov_veteran',
            field=models.BooleanField(default=False, verbose_name='Ветеран Великой Отечественной войны'),
        ),
    ]
