# Generated by Django 5.1.7 on 2025-04-23 13:26

from django.db import migrations, models


def populate_full_name(apps, schema_editor):
    VeteranModel = apps.get_model('veterans', 'VeteranModel')
    for veteran in VeteranModel.objects.all():
        veteran.full_name = f"{veteran.name} {veteran.surname} {veteran.patronymic or ''}".strip()
        veteran.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('veterans', '0004_veteranmodel_is_vov_veteran'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranmodel',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='Полное имя'),
        ),
        migrations.RunPython(populate_full_name, migrations.RunPython.noop),
    ]
