# Generated by Django 5.1.7 on 2025-04-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorialmodel',
            options={'verbose_name': 'Мемориал', 'verbose_name_plural': 'Мемориалы'},
        ),
    ]
