# Generated by Django 5.1.7 on 2025-04-12 09:17

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(storage=api.storages.MediaStorage(), upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='image',
            field=models.ImageField(storage=api.storages.MediaStorage(), upload_to='groups/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(storage=api.storages.MediaStorage(), upload_to='news/', verbose_name='Обложка'),
        ),
    ]
