# Generated by Django 5.1.7 on 2025-04-12 12:08

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_categorymodel_image_alter_groupmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.MediaStorage(), upload_to='news/', verbose_name='Обложка'),
        ),
    ]
