# Generated by Django 5.1.7 on 2025-04-12 12:21

import api.storages
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.groupmodel', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(storage=api.storages.MediaStorage(), upload_to='categories/', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='image',
            field=models.ImageField(storage=api.storages.MediaStorage(), upload_to='groups/', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.categorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.MediaStorage(), upload_to='news/', verbose_name='Загрузить обложку'),
        ),
    ]
