# Generated by Django 5.1.7 on 2025-09-18 22:30

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_categorymodel_group_alter_categorymodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, storage=api.storages.FileStorage(), upload_to='news/', verbose_name='Загрузить файл (pdf)'),
        ),
    ]
